[workspace]
resolver = "3"
members = ["apps/craft-ohos-platform", "apps/photocraft-ohos", "vendor/eframe", "vendor/photocraft-engine"]
exclude = ["upstream", "upstream/crates/*", "upstream/apps/*", "upstream/xtask", "vendor/photocraft-ui-egui"]

[patch.crates-io]
eframe = { path = "vendor/eframe" }

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
codegen-units = 1
panic = "unwind"
strip = "debuginfo"
